language: python

python:
  - "3.6"
  - "2.7"

before_install:
  - cp dipy_web/settings.py.example dipy_web/test_settings.py

install:
  - pip install -r requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" >= "3.6" ]]; then pip install -U defusedxml==0.5.0rc1; fi
  - pip install coverage

script:
  - pytest -svv

after_success: coverage report