language: python

python:
  - "2.7"

before_install:
  - cp dipy_web/settings.py.example dipy_web/test_settings.py

install:
  - pip install -r requirements.txt
  - pip install coverage

matrix:
  include:
    - python: "3.6"
      install: pip install -U defusedxml==0.5.0rc1 # Only for python >=3.6
      
script:
  - pytest -svv

after_success: coverage report